name: PR Agent

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  describe_pr:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PR Agent
        id: pr_agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python git_changes.py
          PR_BODY_CONTENT="$(cat pr_description.md)"
          echo "pr_body<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_BODY_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR Description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BODY: ${{ steps.pr_agent.outputs.pr_body }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --body "$PR_BODY"